apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: gmbot-web
    app.kubernetes.io/instance: gmbot-prod
  name: gmbot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gmbot-web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: gmbot-web
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/gmbot-451416/gm-bot-images/gmbot-web:0.0.3
          name: gmbot-web
          env:
            - name: PORT
              value: "8080"
          envFrom:
          - configMapRef:
              name: gmbot-config-map
          - secretRef:
              name: gmbot-secrets
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 7860
              protocol: TCP
      restartPolicy: Always
