apiVersion: v1
kind: ConfigMap
metadata:
  name: gmbot-config-map
  namespace: default
  labels:
    app.kubernetes.io/instance: gmbot-prod
data:
  CHROMA_HOST: "vector-store"
  CHROMA_PORT: "8000"
  LANGSMITH_TRACING: "true"
  ENV: "prod"
