apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gmbot-web
  name: gmbot-web
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "7860"
      port: 7860
      targetPort: 7860
  selector:
    io.kompose.service: gmbot-web
