apiVersion: v1
kind: Service
metadata:
  labels:
    app: gmbot-web
  name: gmbot-web-lb
spec:
  ports:
    - name: "8080"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: gmbot-web
  loadBalancerIP: 35.193.110.152
  type: LoadBalancer