apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmbot-rw-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: gmbot-rw-storage-class