apiVersion: v1
kind: PersistentVolume
metadata:
    name: gmbot-rw-pv
    annotations:
        gke-gcsfuse/volumes: "true"
    labels:
        app.kubernetes.io/instance: gmbot-prod
spec:
    accessModes:
        - ReadWriteMany
    capacity:
        storage: 5Gi
    storageClassName: gmbot-rw-storage-class
    mountOptions:
        - implicit-dirs
    csi:
        driver: gcsfuse.csi.storage.gke.io
        volumeHandle: gmbot_vector_store
    claimRef:
        name: gmbot-rw-pvc
        namespace: default