apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmbot-game-data-pvc
  namespace: default
  labels:
    app.kubernetes.io/instance: gmbot-prod
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: gmbot-game-data-storage-class